export const ADD_REGULAR: 'ADD_REGULAR' = 'ADD_REGULAR';
export const REMOVE_REGULAR: 'REMOVE_REGULAR' = 'REMOVE_REGULAR';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const REMOVE_BUN: 'REMOVE_BUN' = 'REMOVE_BUN';
export const CHANGE_ORDER: 'CHANGE_ORDER' = 'CHANGE_ORDER';
export const CLEAR_BURGER: 'CLEAR_BURGER' = 'CLEAR_BURGER';

export const GET_ORDER_DETAILS_REQUEST: 'GET_ORDER_DETAILS_REQUEST' =
  'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS' =
  'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAILED: 'GET_ORDER_DETAILS_FAILED' =
  'GET_ORDER_DETAILS_FAILED';

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' =
  'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' =
  'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' =
  'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' =
  'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' =
  'GET_INGREDIENTS_FAILED';

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';
export const OPEN_ORDER: 'OPEN_ORDER' = 'OPEN_ORDER';
export const CLOSE_ORDER: 'CLOSE_ORDER' = 'CLOSE_ORDER';

export const REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST' =
  'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS' =
  'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED: 'REGISTER_USER_FAILED' =
  'REGISTER_USER_FAILED';
export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';
export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';
export const USER_REQUEST: 'USER_REQUEST' = 'USER_REQUEST';
export const USER_SUCCESS: 'USER_SUCCESS' = 'USER_SUCCESS';
export const USER_FAILED: 'USER_FAILED' = 'USER_FAILED';
export const USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST' = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS' = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED: 'USER_UPDATE_FAILED' = 'USER_UPDATE_FAILED';
export const PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST' =
  'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_TOKEN_FAILED: 'PASSWORD_RESET_TOKEN_FAILED' =
  'PASSWORD_RESET_TOKEN_FAILED';
